# Generated by color-listener
# secondary = #A7C4FC
# CL_FG_PRIMARY = darker(secondary), CL_FG_SECONDARY = secondary
# Provide both Bash-bracketed and RAW ANSI variants; pick at runtime
# Bash-bracketed (non-printing markers)
export CL_FG_PRIMARY_BASH="\[\e[38;2;137;161;207m\]"
export CL_FG_SECONDARY_BASH="\[\e[38;2;167;196;252m\]"
export CL_BG_PRIMARY_BASH="\[\e[48;2;137;161;207m\]"
export CL_BG_SECONDARY_BASH="\[\e[48;2;167;196;252m\]"
export CL_RESET_BASH="\[\e[0m\]"
# Raw ANSI (no markers)
export CL_FG_PRIMARY_RAW=$'\e[38;2;137;161;207m'
export CL_FG_SECONDARY_RAW=$'\e[38;2;167;196;252m'
export CL_BG_PRIMARY_RAW=$'\e[48;2;137;161;207m'
export CL_BG_SECONDARY_RAW=$'\e[48;2;167;196;252m'
export CL_RESET_RAW=$'\e[0m'
# Select appropriate set
if [ -n "$BASH_VERSION" ]; then
  export CL_FG_PRIMARY="$CL_FG_PRIMARY_BASH"
  export CL_FG_SECONDARY="$CL_FG_SECONDARY_BASH"
  export CL_BG_PRIMARY="$CL_BG_PRIMARY_BASH"
  export CL_BG_SECONDARY="$CL_BG_SECONDARY_BASH"
  export CL_RESET="$CL_RESET_BASH"
else
  export CL_FG_PRIMARY=$CL_FG_PRIMARY_RAW
  export CL_FG_SECONDARY=$CL_FG_SECONDARY_RAW
  export CL_BG_PRIMARY=$CL_BG_PRIMARY_RAW
  export CL_BG_SECONDARY=$CL_BG_SECONDARY_RAW
  export CL_RESET=$CL_RESET_RAW
fi
