[package]
name = "eww-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenvy = "0.15"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.137"

[[bin]]
name = "eww-rs"
path = "src/main.rs"
