[package]
name = "eww-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.135"

[[bin]]
name = "eww-rs"
path = "main.rs"
